project:
  type: website
  output-dir: docs

website:
  title: "PhilipFosserPortfolioProcects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sleep
        href: Sleep_Analysis.qmd
      - href: Eiendoms_rapport.qmd
        text: Eiendoms investering rapport

format:
  html:
    theme: solar
    link-external-newwindow: TRUE

editor: visual

