project:
  type: website

website:
  title: "PhilipFosserPortfolioProcects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sleep
        href: Sleep_Analysis.qmd

format:
  html:
    theme: solar
    link-external-newwindow: TRUE

editor: visual

